### ISSUE TITLE
The url for app-final-graphql routing doesnt work

### ISSUE THREAD

**Issue by idkjs** [nikgraf/reason-workshop-2#2]
Looks like the url in client.re here https://github.com/nikgraf/reason-workshop-2/blob/181d99faa0b8b2215ad14ed9996c2dba067749e2/app-final-graphql-routing/src/Client.re#L5 is down.

I went ahead and recreated it deployable on zeit. https://github.com/idkjs/weather-api-graphql if that helps.

**Comment by nikgraf** [comment]
This is really great! Much appreciated and will definitely use it for future workshops!
